import React from 'react'

const About = () => {
  return (
    <div className="row gx-0">
  {" "}
  <div className="col-lg-5 mb-4 mb-md-0">
    {" "}
    <div className="d-flex py-md-5">
      {" "}
      <img
        src="https://www.dreamhost.com/blog/wp-content/uploads/2019/01/Blog-experts-opt-750x498.jpg"
        className="w-100 rounded-5 shadow-3-strong"
        id="cta-img-nml-50"
        style={{ zIndex: 10 }}
        alt=""
        aria-controls="#picker-editor"
      />{" "}
    </div>{" "}
  </div>{" "}
  <div className="col-lg-7 mb-4 mb-md-0">
    {" "}
    <div className="bg-warning h-100 rounded-6 p-4 ps-lg-5 text-white d-flex align-items-center">
      {" "}
      <div className="ps-lg-5">
        {" "}
        <h2 className="fw-bold mb-4">Let it surprise you</h2>{" "}
        <p className="">
        Automated Blog Generator System using AI
        </p>{" "}
        <div className="row mb-2">
          {" "}
          
          <div className="col-lg-4">
            {" "}
            <p>
              <i className="fas fa-check-circle me-2" />
              <span>Best quality</span>
            </p>{" "}
          </div>{" "}
          <div className="col-lg-4">
            {" "}
            <p>
              {" "}
              <i className="fas fa-check-circle me-2" />
              <span>Best experience</span>{" "}
            </p>{" "}
          </div>{" "}
        </div>{" "}
        <p>
        The Automated Blog Generation System will simply convert the video content into a blog with the help of AI using the CNN algorithm, a convolutional neural network. This CNN algorithm will extract the speech and convert it into text through the automatic speech and image recognition process. This voice recognition software turns your speech into text with minimal errors.</p>
        <p>
        It can be used for any video be it educational or podcasts like interview videos then for these types of videos blog is generated so that people can refer to the blog also for text-based content. 
        Firstly user has to create an account on the website after that user has to manually upload a video or can link youtube to this website . 
        </p>
        <p>After uploading the video we click on the blog generation page and using the AI algorithm called CNN we convert the speech or audio from the video into the form of a blog that is text content, then we can choose any type of design for the blog page that is to be generated, then we save all the changes made in the blog page and we can publish it on our website. Multiple blogs can be generated by users and published on the website in the form of a listing of the blog. By means of text content in the blog helps to increase the ranking of our website through SEO.  
        </p>{" "}
      </div>{" "}
    </div>{" "}
  </div>{" "}
</div>

  )
}

export default About